// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: chat/chat.proto

package chat

import (
	sdkws "fdim/protocol/sdkws"
	wrapperspb "fdim/protocol/wrapperspb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email"`
	AreaCode      string                 `protobuf:"bytes,2,opt,name=areaCode,proto3" json:"areaCode"`
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phoneNumber,proto3" json:"phoneNumber"`
	DeviceID      string                 `protobuf:"bytes,4,opt,name=deviceID,proto3" json:"deviceID"`
	Platform      int32                  `protobuf:"varint,5,opt,name=platform,proto3" json:"platform"`
	Account       string                 `protobuf:"bytes,6,opt,name=account,proto3" json:"account"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIdentity) Reset() {
	*x = UserIdentity{}
	mi := &file_chat_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdentity) ProtoMessage() {}

func (x *UserIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdentity.ProtoReflect.Descriptor instead.
func (*UserIdentity) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{0}
}

func (x *UserIdentity) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserIdentity) GetAreaCode() string {
	if x != nil {
		return x.AreaCode
	}
	return ""
}

func (x *UserIdentity) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UserIdentity) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *UserIdentity) GetPlatform() int32 {
	if x != nil {
		return x.Platform
	}
	return 0
}

func (x *UserIdentity) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type UpdateUserInfoReq struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	UserID           string                  `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	Account          *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=account,proto3" json:"account"`
	PhoneNumber      *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=phoneNumber,proto3" json:"phoneNumber"`
	AreaCode         *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=areaCode,proto3" json:"areaCode"`
	Email            *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=email,proto3" json:"email"`
	Nickname         *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=nickname,proto3" json:"nickname"`
	FaceURL          *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=faceURL,proto3" json:"faceURL"`
	Gender           *wrapperspb.Int32Value  `protobuf:"bytes,8,opt,name=gender,proto3" json:"gender"`
	Level            *wrapperspb.Int32Value  `protobuf:"bytes,9,opt,name=level,proto3" json:"level"`
	Birth            *wrapperspb.Int64Value  `protobuf:"bytes,10,opt,name=birth,proto3" json:"birth"`
	AllowAddFriend   *wrapperspb.Int32Value  `protobuf:"bytes,11,opt,name=allowAddFriend,proto3" json:"allowAddFriend"`
	AllowBeep        *wrapperspb.Int32Value  `protobuf:"bytes,12,opt,name=allowBeep,proto3" json:"allowBeep"`
	AllowVibration   *wrapperspb.Int32Value  `protobuf:"bytes,13,opt,name=allowVibration,proto3" json:"allowVibration"`
	GlobalRecvMsgOpt *wrapperspb.Int32Value  `protobuf:"bytes,14,opt,name=globalRecvMsgOpt,proto3" json:"globalRecvMsgOpt"`
	RegisterType     *wrapperspb.Int32Value  `protobuf:"bytes,15,opt,name=RegisterType,proto3" json:"RegisterType"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateUserInfoReq) Reset() {
	*x = UpdateUserInfoReq{}
	mi := &file_chat_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoReq) ProtoMessage() {}

func (x *UpdateUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoReq.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoReq) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateUserInfoReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UpdateUserInfoReq) GetAccount() *wrapperspb.StringValue {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *UpdateUserInfoReq) GetPhoneNumber() *wrapperspb.StringValue {
	if x != nil {
		return x.PhoneNumber
	}
	return nil
}

func (x *UpdateUserInfoReq) GetAreaCode() *wrapperspb.StringValue {
	if x != nil {
		return x.AreaCode
	}
	return nil
}

func (x *UpdateUserInfoReq) GetEmail() *wrapperspb.StringValue {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *UpdateUserInfoReq) GetNickname() *wrapperspb.StringValue {
	if x != nil {
		return x.Nickname
	}
	return nil
}

func (x *UpdateUserInfoReq) GetFaceURL() *wrapperspb.StringValue {
	if x != nil {
		return x.FaceURL
	}
	return nil
}

func (x *UpdateUserInfoReq) GetGender() *wrapperspb.Int32Value {
	if x != nil {
		return x.Gender
	}
	return nil
}

func (x *UpdateUserInfoReq) GetLevel() *wrapperspb.Int32Value {
	if x != nil {
		return x.Level
	}
	return nil
}

func (x *UpdateUserInfoReq) GetBirth() *wrapperspb.Int64Value {
	if x != nil {
		return x.Birth
	}
	return nil
}

func (x *UpdateUserInfoReq) GetAllowAddFriend() *wrapperspb.Int32Value {
	if x != nil {
		return x.AllowAddFriend
	}
	return nil
}

func (x *UpdateUserInfoReq) GetAllowBeep() *wrapperspb.Int32Value {
	if x != nil {
		return x.AllowBeep
	}
	return nil
}

func (x *UpdateUserInfoReq) GetAllowVibration() *wrapperspb.Int32Value {
	if x != nil {
		return x.AllowVibration
	}
	return nil
}

func (x *UpdateUserInfoReq) GetGlobalRecvMsgOpt() *wrapperspb.Int32Value {
	if x != nil {
		return x.GlobalRecvMsgOpt
	}
	return nil
}

func (x *UpdateUserInfoReq) GetRegisterType() *wrapperspb.Int32Value {
	if x != nil {
		return x.RegisterType
	}
	return nil
}

type UpdateUserInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FaceUrl       string                 `protobuf:"bytes,1,opt,name=faceUrl,proto3" json:"faceUrl"`
	NickName      string                 `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInfoResp) Reset() {
	*x = UpdateUserInfoResp{}
	mi := &file_chat_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoResp) ProtoMessage() {}

func (x *UpdateUserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoResp.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoResp) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserInfoResp) GetFaceUrl() string {
	if x != nil {
		return x.FaceUrl
	}
	return ""
}

func (x *UpdateUserInfoResp) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

type FindUserPublicInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIDs       []string               `protobuf:"bytes,1,rep,name=userIDs,proto3" json:"userIDs"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindUserPublicInfoReq) Reset() {
	*x = FindUserPublicInfoReq{}
	mi := &file_chat_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindUserPublicInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserPublicInfoReq) ProtoMessage() {}

func (x *FindUserPublicInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserPublicInfoReq.ProtoReflect.Descriptor instead.
func (*FindUserPublicInfoReq) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{3}
}

func (x *FindUserPublicInfoReq) GetUserIDs() []string {
	if x != nil {
		return x.UserIDs
	}
	return nil
}

type FindUserPublicInfoResp struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Users         []*sdkws.ChatUserPublicInfo `protobuf:"bytes,1,rep,name=users,proto3" json:"users"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindUserPublicInfoResp) Reset() {
	*x = FindUserPublicInfoResp{}
	mi := &file_chat_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindUserPublicInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserPublicInfoResp) ProtoMessage() {}

func (x *FindUserPublicInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserPublicInfoResp.ProtoReflect.Descriptor instead.
func (*FindUserPublicInfoResp) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{4}
}

func (x *FindUserPublicInfoResp) GetUsers() []*sdkws.ChatUserPublicInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

type SearchUserPublicInfoReq struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Keyword       string                   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword"`
	Pagination    *sdkws.RequestPagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination"`
	Genders       int32                    `protobuf:"varint,3,opt,name=genders,proto3" json:"genders"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserPublicInfoReq) Reset() {
	*x = SearchUserPublicInfoReq{}
	mi := &file_chat_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserPublicInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserPublicInfoReq) ProtoMessage() {}

func (x *SearchUserPublicInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserPublicInfoReq.ProtoReflect.Descriptor instead.
func (*SearchUserPublicInfoReq) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{5}
}

func (x *SearchUserPublicInfoReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchUserPublicInfoReq) GetPagination() *sdkws.RequestPagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *SearchUserPublicInfoReq) GetGenders() int32 {
	if x != nil {
		return x.Genders
	}
	return 0
}

type SearchUserPublicInfoResp struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Total         uint32                      `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	Users         []*sdkws.ChatUserPublicInfo `protobuf:"bytes,2,rep,name=users,proto3" json:"users"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserPublicInfoResp) Reset() {
	*x = SearchUserPublicInfoResp{}
	mi := &file_chat_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserPublicInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserPublicInfoResp) ProtoMessage() {}

func (x *SearchUserPublicInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserPublicInfoResp.ProtoReflect.Descriptor instead.
func (*SearchUserPublicInfoResp) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{6}
}

func (x *SearchUserPublicInfoResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchUserPublicInfoResp) GetUsers() []*sdkws.ChatUserPublicInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

type FindUserFullInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIDs       []string               `protobuf:"bytes,1,rep,name=userIDs,proto3" json:"userIDs"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindUserFullInfoReq) Reset() {
	*x = FindUserFullInfoReq{}
	mi := &file_chat_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindUserFullInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserFullInfoReq) ProtoMessage() {}

func (x *FindUserFullInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserFullInfoReq.ProtoReflect.Descriptor instead.
func (*FindUserFullInfoReq) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{7}
}

func (x *FindUserFullInfoReq) GetUserIDs() []string {
	if x != nil {
		return x.UserIDs
	}
	return nil
}

type FindUserFullInfoResp struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Users         []*sdkws.ChatUserFullInfo `protobuf:"bytes,1,rep,name=users,proto3" json:"users"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindUserFullInfoResp) Reset() {
	*x = FindUserFullInfoResp{}
	mi := &file_chat_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindUserFullInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserFullInfoResp) ProtoMessage() {}

func (x *FindUserFullInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserFullInfoResp.ProtoReflect.Descriptor instead.
func (*FindUserFullInfoResp) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{8}
}

func (x *FindUserFullInfoResp) GetUsers() []*sdkws.ChatUserFullInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

type SendVerifyCodeReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UsedFor        int32                  `protobuf:"varint,1,opt,name=usedFor,proto3" json:"usedFor"`
	Ip             string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip"`
	InvitationCode string                 `protobuf:"bytes,3,opt,name=invitationCode,proto3" json:"invitationCode"`
	DeviceID       string                 `protobuf:"bytes,4,opt,name=deviceID,proto3" json:"deviceID"`
	Platform       int32                  `protobuf:"varint,5,opt,name=platform,proto3" json:"platform"`
	AreaCode       string                 `protobuf:"bytes,6,opt,name=areaCode,proto3" json:"areaCode"`
	PhoneNumber    string                 `protobuf:"bytes,7,opt,name=phoneNumber,proto3" json:"phoneNumber"`
	Email          string                 `protobuf:"bytes,8,opt,name=email,proto3" json:"email"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendVerifyCodeReq) Reset() {
	*x = SendVerifyCodeReq{}
	mi := &file_chat_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendVerifyCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendVerifyCodeReq) ProtoMessage() {}

func (x *SendVerifyCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendVerifyCodeReq.ProtoReflect.Descriptor instead.
func (*SendVerifyCodeReq) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{9}
}

func (x *SendVerifyCodeReq) GetUsedFor() int32 {
	if x != nil {
		return x.UsedFor
	}
	return 0
}

func (x *SendVerifyCodeReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *SendVerifyCodeReq) GetInvitationCode() string {
	if x != nil {
		return x.InvitationCode
	}
	return ""
}

func (x *SendVerifyCodeReq) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *SendVerifyCodeReq) GetPlatform() int32 {
	if x != nil {
		return x.Platform
	}
	return 0
}

func (x *SendVerifyCodeReq) GetAreaCode() string {
	if x != nil {
		return x.AreaCode
	}
	return ""
}

func (x *SendVerifyCodeReq) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *SendVerifyCodeReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SendVerifyCodeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendVerifyCodeResp) Reset() {
	*x = SendVerifyCodeResp{}
	mi := &file_chat_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendVerifyCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendVerifyCodeResp) ProtoMessage() {}

func (x *SendVerifyCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendVerifyCodeResp.ProtoReflect.Descriptor instead.
func (*SendVerifyCodeResp) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{10}
}

type VerifyCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AreaCode      string                 `protobuf:"bytes,1,opt,name=areaCode,proto3" json:"areaCode"`
	PhoneNumber   string                 `protobuf:"bytes,2,opt,name=phoneNumber,proto3" json:"phoneNumber"`
	VerifyCode    string                 `protobuf:"bytes,3,opt,name=verifyCode,proto3" json:"verifyCode"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCodeReq) Reset() {
	*x = VerifyCodeReq{}
	mi := &file_chat_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCodeReq) ProtoMessage() {}

func (x *VerifyCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCodeReq.ProtoReflect.Descriptor instead.
func (*VerifyCodeReq) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{11}
}

func (x *VerifyCodeReq) GetAreaCode() string {
	if x != nil {
		return x.AreaCode
	}
	return ""
}

func (x *VerifyCodeReq) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *VerifyCodeReq) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

func (x *VerifyCodeReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type VerifyCodeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCodeResp) Reset() {
	*x = VerifyCodeResp{}
	mi := &file_chat_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCodeResp) ProtoMessage() {}

func (x *VerifyCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCodeResp.ProtoReflect.Descriptor instead.
func (*VerifyCodeResp) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{12}
}

type RegisterUserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname"`
	FaceURL       string                 `protobuf:"bytes,3,opt,name=faceURL,proto3" json:"faceURL"`
	Birth         int64                  `protobuf:"varint,4,opt,name=birth,proto3" json:"birth"`
	Gender        int32                  `protobuf:"varint,5,opt,name=gender,proto3" json:"gender"`
	AreaCode      string                 `protobuf:"bytes,6,opt,name=areaCode,proto3" json:"areaCode"`
	PhoneNumber   string                 `protobuf:"bytes,7,opt,name=phoneNumber,proto3" json:"phoneNumber"`
	Email         string                 `protobuf:"bytes,8,opt,name=email,proto3" json:"email"`
	Account       string                 `protobuf:"bytes,9,opt,name=account,proto3" json:"account"`
	Password      string                 `protobuf:"bytes,10,opt,name=password,proto3" json:"password"`
	RegisterType  int32                  `protobuf:"varint,11,opt,name=RegisterType,proto3" json:"RegisterType"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserInfo) Reset() {
	*x = RegisterUserInfo{}
	mi := &file_chat_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserInfo) ProtoMessage() {}

func (x *RegisterUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserInfo.ProtoReflect.Descriptor instead.
func (*RegisterUserInfo) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterUserInfo) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *RegisterUserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RegisterUserInfo) GetFaceURL() string {
	if x != nil {
		return x.FaceURL
	}
	return ""
}

func (x *RegisterUserInfo) GetBirth() int64 {
	if x != nil {
		return x.Birth
	}
	return 0
}

func (x *RegisterUserInfo) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *RegisterUserInfo) GetAreaCode() string {
	if x != nil {
		return x.AreaCode
	}
	return ""
}

func (x *RegisterUserInfo) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *RegisterUserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterUserInfo) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *RegisterUserInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterUserInfo) GetRegisterType() int32 {
	if x != nil {
		return x.RegisterType
	}
	return 0
}

type RegisterUserReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InvitationCode string                 `protobuf:"bytes,1,opt,name=invitationCode,proto3" json:"invitationCode"`
	VerifyCode     string                 `protobuf:"bytes,2,opt,name=verifyCode,proto3" json:"verifyCode"`
	Ip             string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip"`
	DeviceID       string                 `protobuf:"bytes,4,opt,name=deviceID,proto3" json:"deviceID"`
	Platform       int32                  `protobuf:"varint,5,opt,name=platform,proto3" json:"platform"`
	AutoLogin      bool                   `protobuf:"varint,6,opt,name=autoLogin,proto3" json:"autoLogin"`
	User           *RegisterUserInfo      `protobuf:"bytes,7,opt,name=user,proto3" json:"user"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterUserReq) Reset() {
	*x = RegisterUserReq{}
	mi := &file_chat_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserReq) ProtoMessage() {}

func (x *RegisterUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserReq.ProtoReflect.Descriptor instead.
func (*RegisterUserReq) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{14}
}

func (x *RegisterUserReq) GetInvitationCode() string {
	if x != nil {
		return x.InvitationCode
	}
	return ""
}

func (x *RegisterUserReq) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

func (x *RegisterUserReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RegisterUserReq) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *RegisterUserReq) GetPlatform() int32 {
	if x != nil {
		return x.Platform
	}
	return 0
}

func (x *RegisterUserReq) GetAutoLogin() bool {
	if x != nil {
		return x.AutoLogin
	}
	return false
}

func (x *RegisterUserReq) GetUser() *RegisterUserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type RegisterUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	ChatToken     string                 `protobuf:"bytes,3,opt,name=chatToken,proto3" json:"chatToken"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserResp) Reset() {
	*x = RegisterUserResp{}
	mi := &file_chat_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResp) ProtoMessage() {}

func (x *RegisterUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResp.ProtoReflect.Descriptor instead.
func (*RegisterUserResp) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{15}
}

func (x *RegisterUserResp) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *RegisterUserResp) GetChatToken() string {
	if x != nil {
		return x.ChatToken
	}
	return ""
}

type AddUserAccountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip"`
	DeviceID      string                 `protobuf:"bytes,2,opt,name=deviceID,proto3" json:"deviceID"`
	Platform      int32                  `protobuf:"varint,3,opt,name=platform,proto3" json:"platform"`
	User          *RegisterUserInfo      `protobuf:"bytes,4,opt,name=user,proto3" json:"user"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserAccountReq) Reset() {
	*x = AddUserAccountReq{}
	mi := &file_chat_chat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserAccountReq) ProtoMessage() {}

func (x *AddUserAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserAccountReq.ProtoReflect.Descriptor instead.
func (*AddUserAccountReq) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{16}
}

func (x *AddUserAccountReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AddUserAccountReq) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *AddUserAccountReq) GetPlatform() int32 {
	if x != nil {
		return x.Platform
	}
	return 0
}

func (x *AddUserAccountReq) GetUser() *RegisterUserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type AddUserAccountResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserAccountResp) Reset() {
	*x = AddUserAccountResp{}
	mi := &file_chat_chat_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserAccountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserAccountResp) ProtoMessage() {}

func (x *AddUserAccountResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserAccountResp.ProtoReflect.Descriptor instead.
func (*AddUserAccountResp) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{17}
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AreaCode      string                 `protobuf:"bytes,1,opt,name=areaCode,proto3" json:"areaCode"`
	PhoneNumber   string                 `protobuf:"bytes,2,opt,name=phoneNumber,proto3" json:"phoneNumber"`
	VerifyCode    string                 `protobuf:"bytes,3,opt,name=verifyCode,proto3" json:"verifyCode"`
	Account       string                 `protobuf:"bytes,4,opt,name=account,proto3" json:"account"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password"`
	Platform      int32                  `protobuf:"varint,6,opt,name=platform,proto3" json:"platform"`
	DeviceID      string                 `protobuf:"bytes,7,opt,name=deviceID,proto3" json:"deviceID"`
	Ip            string                 `protobuf:"bytes,8,opt,name=ip,proto3" json:"ip"`
	Email         string                 `protobuf:"bytes,9,opt,name=email,proto3" json:"email"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_chat_chat_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{18}
}

func (x *LoginReq) GetAreaCode() string {
	if x != nil {
		return x.AreaCode
	}
	return ""
}

func (x *LoginReq) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *LoginReq) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

func (x *LoginReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginReq) GetPlatform() int32 {
	if x != nil {
		return x.Platform
	}
	return 0
}

func (x *LoginReq) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *LoginReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *LoginReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ResetPasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AreaCode      string                 `protobuf:"bytes,1,opt,name=areaCode,proto3" json:"areaCode"`
	PhoneNumber   string                 `protobuf:"bytes,2,opt,name=phoneNumber,proto3" json:"phoneNumber"`
	VerifyCode    string                 `protobuf:"bytes,3,opt,name=verifyCode,proto3" json:"verifyCode"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordReq) Reset() {
	*x = ResetPasswordReq{}
	mi := &file_chat_chat_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordReq) ProtoMessage() {}

func (x *ResetPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordReq.ProtoReflect.Descriptor instead.
func (*ResetPasswordReq) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{19}
}

func (x *ResetPasswordReq) GetAreaCode() string {
	if x != nil {
		return x.AreaCode
	}
	return ""
}

func (x *ResetPasswordReq) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *ResetPasswordReq) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

func (x *ResetPasswordReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ResetPasswordReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ResetPasswordResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordResp) Reset() {
	*x = ResetPasswordResp{}
	mi := &file_chat_chat_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordResp) ProtoMessage() {}

func (x *ResetPasswordResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordResp.ProtoReflect.Descriptor instead.
func (*ResetPasswordResp) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{20}
}

type ChangePasswordReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserID          string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	CurrentPassword string                 `protobuf:"bytes,2,opt,name=currentPassword,proto3" json:"currentPassword"`
	NewPassword     string                 `protobuf:"bytes,3,opt,name=newPassword,proto3" json:"newPassword"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangePasswordReq) Reset() {
	*x = ChangePasswordReq{}
	mi := &file_chat_chat_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordReq) ProtoMessage() {}

func (x *ChangePasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordReq.ProtoReflect.Descriptor instead.
func (*ChangePasswordReq) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{21}
}

func (x *ChangePasswordReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *ChangePasswordReq) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

func (x *ChangePasswordReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ChangePasswordResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResp) Reset() {
	*x = ChangePasswordResp{}
	mi := &file_chat_chat_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResp) ProtoMessage() {}

func (x *ChangePasswordResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResp.ProtoReflect.Descriptor instead.
func (*ChangePasswordResp) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{22}
}

type FindUserAccountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIDs       []string               `protobuf:"bytes,1,rep,name=userIDs,proto3" json:"userIDs"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindUserAccountReq) Reset() {
	*x = FindUserAccountReq{}
	mi := &file_chat_chat_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindUserAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserAccountReq) ProtoMessage() {}

func (x *FindUserAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserAccountReq.ProtoReflect.Descriptor instead.
func (*FindUserAccountReq) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{23}
}

func (x *FindUserAccountReq) GetUserIDs() []string {
	if x != nil {
		return x.UserIDs
	}
	return nil
}

type FindUserAccountResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserAccountMap map[string]string      `protobuf:"bytes,1,rep,name=userAccountMap,proto3" json:"userAccountMap" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // userID  account
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FindUserAccountResp) Reset() {
	*x = FindUserAccountResp{}
	mi := &file_chat_chat_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindUserAccountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserAccountResp) ProtoMessage() {}

func (x *FindUserAccountResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserAccountResp.ProtoReflect.Descriptor instead.
func (*FindUserAccountResp) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{24}
}

func (x *FindUserAccountResp) GetUserAccountMap() map[string]string {
	if x != nil {
		return x.UserAccountMap
	}
	return nil
}

type FindAccountUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []string               `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAccountUserReq) Reset() {
	*x = FindAccountUserReq{}
	mi := &file_chat_chat_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAccountUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAccountUserReq) ProtoMessage() {}

func (x *FindAccountUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAccountUserReq.ProtoReflect.Descriptor instead.
func (*FindAccountUserReq) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{25}
}

func (x *FindAccountUserReq) GetAccounts() []string {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type FindAccountUserResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountUserMap map[string]string      `protobuf:"bytes,1,rep,name=accountUserMap,proto3" json:"accountUserMap" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // account  userID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FindAccountUserResp) Reset() {
	*x = FindAccountUserResp{}
	mi := &file_chat_chat_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAccountUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAccountUserResp) ProtoMessage() {}

func (x *FindAccountUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAccountUserResp.ProtoReflect.Descriptor instead.
func (*FindAccountUserResp) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{26}
}

func (x *FindAccountUserResp) GetAccountUserMap() map[string]string {
	if x != nil {
		return x.AccountUserMap
	}
	return nil
}

type SignalRecord struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	FileName        string                      `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName"`
	MediaType       string                      `protobuf:"bytes,2,opt,name=mediaType,proto3" json:"mediaType"`
	RoomType        string                      `protobuf:"bytes,3,opt,name=roomType,proto3" json:"roomType"`
	SenderID        string                      `protobuf:"bytes,4,opt,name=senderID,proto3" json:"senderID"`
	SenderNickname  string                      `protobuf:"bytes,5,opt,name=senderNickname,proto3" json:"senderNickname"`
	RecvID          string                      `protobuf:"bytes,6,opt,name=recvID,proto3" json:"recvID"`
	RecvNickname    string                      `protobuf:"bytes,7,opt,name=recvNickname,proto3" json:"recvNickname"`
	GroupID         string                      `protobuf:"bytes,8,opt,name=groupID,proto3" json:"groupID"`
	GroupName       string                      `protobuf:"bytes,9,opt,name=groupName,proto3" json:"groupName"`
	InviterUserList []*sdkws.ChatUserPublicInfo `protobuf:"bytes,10,rep,name=inviterUserList,proto3" json:"inviterUserList"`
	Duration        int32                       `protobuf:"varint,11,opt,name=duration,proto3" json:"duration"`
	CreateTime      int64                       `protobuf:"varint,12,opt,name=createTime,proto3" json:"createTime"`
	Size            string                      `protobuf:"bytes,13,opt,name=size,proto3" json:"size"`
	DownloadURL     string                      `protobuf:"bytes,14,opt,name=downloadURL,proto3" json:"downloadURL"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SignalRecord) Reset() {
	*x = SignalRecord{}
	mi := &file_chat_chat_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRecord) ProtoMessage() {}

func (x *SignalRecord) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRecord.ProtoReflect.Descriptor instead.
func (*SignalRecord) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{27}
}

func (x *SignalRecord) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *SignalRecord) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *SignalRecord) GetRoomType() string {
	if x != nil {
		return x.RoomType
	}
	return ""
}

func (x *SignalRecord) GetSenderID() string {
	if x != nil {
		return x.SenderID
	}
	return ""
}

func (x *SignalRecord) GetSenderNickname() string {
	if x != nil {
		return x.SenderNickname
	}
	return ""
}

func (x *SignalRecord) GetRecvID() string {
	if x != nil {
		return x.RecvID
	}
	return ""
}

func (x *SignalRecord) GetRecvNickname() string {
	if x != nil {
		return x.RecvNickname
	}
	return ""
}

func (x *SignalRecord) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *SignalRecord) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *SignalRecord) GetInviterUserList() []*sdkws.ChatUserPublicInfo {
	if x != nil {
		return x.InviterUserList
	}
	return nil
}

func (x *SignalRecord) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *SignalRecord) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *SignalRecord) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *SignalRecord) GetDownloadURL() string {
	if x != nil {
		return x.DownloadURL
	}
	return ""
}

type FDIMCallbackReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FDIMCallbackReq) Reset() {
	*x = FDIMCallbackReq{}
	mi := &file_chat_chat_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FDIMCallbackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FDIMCallbackReq) ProtoMessage() {}

func (x *FDIMCallbackReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FDIMCallbackReq.ProtoReflect.Descriptor instead.
func (*FDIMCallbackReq) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{28}
}

func (x *FDIMCallbackReq) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *FDIMCallbackReq) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type FDIMCallbackResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FDIMCallbackResp) Reset() {
	*x = FDIMCallbackResp{}
	mi := &file_chat_chat_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FDIMCallbackResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FDIMCallbackResp) ProtoMessage() {}

func (x *FDIMCallbackResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FDIMCallbackResp.ProtoReflect.Descriptor instead.
func (*FDIMCallbackResp) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{29}
}

type SearchUserFullInfoReq struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Keyword       string                   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword"`
	Pagination    *sdkws.RequestPagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination"`
	Genders       int32                    `protobuf:"varint,3,opt,name=genders,proto3" json:"genders"`
	Normal        int32                    `protobuf:"varint,4,opt,name=normal,proto3" json:"normal"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserFullInfoReq) Reset() {
	*x = SearchUserFullInfoReq{}
	mi := &file_chat_chat_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserFullInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserFullInfoReq) ProtoMessage() {}

func (x *SearchUserFullInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserFullInfoReq.ProtoReflect.Descriptor instead.
func (*SearchUserFullInfoReq) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{30}
}

func (x *SearchUserFullInfoReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchUserFullInfoReq) GetPagination() *sdkws.RequestPagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *SearchUserFullInfoReq) GetGenders() int32 {
	if x != nil {
		return x.Genders
	}
	return 0
}

func (x *SearchUserFullInfoReq) GetNormal() int32 {
	if x != nil {
		return x.Normal
	}
	return 0
}

type SearchUserFullInfoResp struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Total         uint32                    `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	Users         []*sdkws.ChatUserFullInfo `protobuf:"bytes,2,rep,name=users,proto3" json:"users"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserFullInfoResp) Reset() {
	*x = SearchUserFullInfoResp{}
	mi := &file_chat_chat_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserFullInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserFullInfoResp) ProtoMessage() {}

func (x *SearchUserFullInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserFullInfoResp.ProtoReflect.Descriptor instead.
func (*SearchUserFullInfoResp) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{31}
}

func (x *SearchUserFullInfoResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchUserFullInfoResp) GetUsers() []*sdkws.ChatUserFullInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

type UserLoginCountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         int64                  `protobuf:"varint,1,opt,name=start,proto3" json:"start"`
	End           int64                  `protobuf:"varint,2,opt,name=end,proto3" json:"end"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginCountReq) Reset() {
	*x = UserLoginCountReq{}
	mi := &file_chat_chat_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginCountReq) ProtoMessage() {}

func (x *UserLoginCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginCountReq.ProtoReflect.Descriptor instead.
func (*UserLoginCountReq) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{32}
}

func (x *UserLoginCountReq) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *UserLoginCountReq) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

type UserLoginCountResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoginCount    int64                  `protobuf:"varint,1,opt,name=loginCount,proto3" json:"loginCount"`
	UnloginCount  int64                  `protobuf:"varint,2,opt,name=unloginCount,proto3" json:"unloginCount"`
	Count         map[string]int64       `protobuf:"bytes,3,rep,name=count,proto3" json:"count" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginCountResp) Reset() {
	*x = UserLoginCountResp{}
	mi := &file_chat_chat_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginCountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginCountResp) ProtoMessage() {}

func (x *UserLoginCountResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginCountResp.ProtoReflect.Descriptor instead.
func (*UserLoginCountResp) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{33}
}

func (x *UserLoginCountResp) GetLoginCount() int64 {
	if x != nil {
		return x.LoginCount
	}
	return 0
}

func (x *UserLoginCountResp) GetUnloginCount() int64 {
	if x != nil {
		return x.UnloginCount
	}
	return 0
}

func (x *UserLoginCountResp) GetCount() map[string]int64 {
	if x != nil {
		return x.Count
	}
	return nil
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatToken     string                 `protobuf:"bytes,2,opt,name=chatToken,proto3" json:"chatToken"`
	UserID        string                 `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_chat_chat_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{34}
}

func (x *LoginResp) GetChatToken() string {
	if x != nil {
		return x.ChatToken
	}
	return ""
}

func (x *LoginResp) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type SearchUserInfoReq struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Keyword       string                   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword"`
	Pagination    *sdkws.RequestPagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination"`
	Genders       []int32                  `protobuf:"varint,3,rep,packed,name=genders,proto3" json:"genders"`
	UserIDs       []string                 `protobuf:"bytes,4,rep,name=userIDs,proto3" json:"userIDs"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserInfoReq) Reset() {
	*x = SearchUserInfoReq{}
	mi := &file_chat_chat_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserInfoReq) ProtoMessage() {}

func (x *SearchUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserInfoReq.ProtoReflect.Descriptor instead.
func (*SearchUserInfoReq) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{35}
}

func (x *SearchUserInfoReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchUserInfoReq) GetPagination() *sdkws.RequestPagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *SearchUserInfoReq) GetGenders() []int32 {
	if x != nil {
		return x.Genders
	}
	return nil
}

func (x *SearchUserInfoReq) GetUserIDs() []string {
	if x != nil {
		return x.UserIDs
	}
	return nil
}

type SearchUserInfoResp struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Total         uint32                    `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	Users         []*sdkws.ChatUserFullInfo `protobuf:"bytes,2,rep,name=users,proto3" json:"users"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserInfoResp) Reset() {
	*x = SearchUserInfoResp{}
	mi := &file_chat_chat_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserInfoResp) ProtoMessage() {}

func (x *SearchUserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserInfoResp.ProtoReflect.Descriptor instead.
func (*SearchUserInfoResp) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{36}
}

func (x *SearchUserInfoResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SearchUserInfoResp) GetUsers() []*sdkws.ChatUserFullInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetTokenForVideoMeetingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          string                 `protobuf:"bytes,1,opt,name=room,proto3" json:"room"`
	Identity      string                 `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenForVideoMeetingReq) Reset() {
	*x = GetTokenForVideoMeetingReq{}
	mi := &file_chat_chat_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenForVideoMeetingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenForVideoMeetingReq) ProtoMessage() {}

func (x *GetTokenForVideoMeetingReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenForVideoMeetingReq.ProtoReflect.Descriptor instead.
func (*GetTokenForVideoMeetingReq) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{37}
}

func (x *GetTokenForVideoMeetingReq) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *GetTokenForVideoMeetingReq) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type GetTokenForVideoMeetingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerUrl     string                 `protobuf:"bytes,1,opt,name=serverUrl,proto3" json:"serverUrl"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenForVideoMeetingResp) Reset() {
	*x = GetTokenForVideoMeetingResp{}
	mi := &file_chat_chat_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenForVideoMeetingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenForVideoMeetingResp) ProtoMessage() {}

func (x *GetTokenForVideoMeetingResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenForVideoMeetingResp.ProtoReflect.Descriptor instead.
func (*GetTokenForVideoMeetingResp) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{38}
}

func (x *GetTokenForVideoMeetingResp) GetServerUrl() string {
	if x != nil {
		return x.ServerUrl
	}
	return ""
}

func (x *GetTokenForVideoMeetingResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CheckUserExistReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *RegisterUserInfo      `protobuf:"bytes,1,opt,name=user,proto3" json:"user"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserExistReq) Reset() {
	*x = CheckUserExistReq{}
	mi := &file_chat_chat_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserExistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserExistReq) ProtoMessage() {}

func (x *CheckUserExistReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserExistReq.ProtoReflect.Descriptor instead.
func (*CheckUserExistReq) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{39}
}

func (x *CheckUserExistReq) GetUser() *RegisterUserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type CheckUserExistResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Userid        string                 `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid"`
	IsRegistered  bool                   `protobuf:"varint,2,opt,name=isRegistered,proto3" json:"isRegistered"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserExistResp) Reset() {
	*x = CheckUserExistResp{}
	mi := &file_chat_chat_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserExistResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserExistResp) ProtoMessage() {}

func (x *CheckUserExistResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserExistResp.ProtoReflect.Descriptor instead.
func (*CheckUserExistResp) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{40}
}

func (x *CheckUserExistResp) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

func (x *CheckUserExistResp) GetIsRegistered() bool {
	if x != nil {
		return x.IsRegistered
	}
	return false
}

type DelUserAccountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIDs       []string               `protobuf:"bytes,1,rep,name=userIDs,proto3" json:"userIDs"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelUserAccountReq) Reset() {
	*x = DelUserAccountReq{}
	mi := &file_chat_chat_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelUserAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelUserAccountReq) ProtoMessage() {}

func (x *DelUserAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelUserAccountReq.ProtoReflect.Descriptor instead.
func (*DelUserAccountReq) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{41}
}

func (x *DelUserAccountReq) GetUserIDs() []string {
	if x != nil {
		return x.UserIDs
	}
	return nil
}

type DelUserAccountResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelUserAccountResp) Reset() {
	*x = DelUserAccountResp{}
	mi := &file_chat_chat_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelUserAccountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelUserAccountResp) ProtoMessage() {}

func (x *DelUserAccountResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelUserAccountResp.ProtoReflect.Descriptor instead.
func (*DelUserAccountResp) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{42}
}

type SetAllowRegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AllowRegister bool                   `protobuf:"varint,1,opt,name=allowRegister,proto3" json:"allowRegister"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAllowRegisterReq) Reset() {
	*x = SetAllowRegisterReq{}
	mi := &file_chat_chat_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAllowRegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAllowRegisterReq) ProtoMessage() {}

func (x *SetAllowRegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAllowRegisterReq.ProtoReflect.Descriptor instead.
func (*SetAllowRegisterReq) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{43}
}

func (x *SetAllowRegisterReq) GetAllowRegister() bool {
	if x != nil {
		return x.AllowRegister
	}
	return false
}

type SetAllowRegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAllowRegisterResp) Reset() {
	*x = SetAllowRegisterResp{}
	mi := &file_chat_chat_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAllowRegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAllowRegisterResp) ProtoMessage() {}

func (x *SetAllowRegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAllowRegisterResp.ProtoReflect.Descriptor instead.
func (*SetAllowRegisterResp) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{44}
}

type GetAllowRegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllowRegisterReq) Reset() {
	*x = GetAllowRegisterReq{}
	mi := &file_chat_chat_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllowRegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllowRegisterReq) ProtoMessage() {}

func (x *GetAllowRegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllowRegisterReq.ProtoReflect.Descriptor instead.
func (*GetAllowRegisterReq) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{45}
}

type GetAllowRegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AllowRegister bool                   `protobuf:"varint,1,opt,name=allowRegister,proto3" json:"allowRegister"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllowRegisterResp) Reset() {
	*x = GetAllowRegisterResp{}
	mi := &file_chat_chat_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllowRegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllowRegisterResp) ProtoMessage() {}

func (x *GetAllowRegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chat_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllowRegisterResp.ProtoReflect.Descriptor instead.
func (*GetAllowRegisterResp) Descriptor() ([]byte, []int) {
	return file_chat_chat_proto_rawDescGZIP(), []int{46}
}

func (x *GetAllowRegisterResp) GetAllowRegister() bool {
	if x != nil {
		return x.AllowRegister
	}
	return false
}

var File_chat_chat_proto protoreflect.FileDescriptor

const file_chat_chat_proto_rawDesc = "" +
	"\n" +
	"\x0fchat/chat.proto\x12\tfdim.chat\x1a\x11sdkws/sdkws.proto\x1a\x1bwrapperspb/wrapperspb.proto\"\xb4\x01\n" +
	"\fUserIdentity\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bareaCode\x18\x02 \x01(\tR\bareaCode\x12 \n" +
	"\vphoneNumber\x18\x03 \x01(\tR\vphoneNumber\x12\x1a\n" +
	"\bdeviceID\x18\x04 \x01(\tR\bdeviceID\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\x05R\bplatform\x12\x18\n" +
	"\aaccount\x18\x06 \x01(\tR\aaccount\"\xd1\x06\n" +
	"\x11UpdateUserInfoReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x124\n" +
	"\aaccount\x18\x02 \x01(\v2\x1a.fdim.protobuf.StringValueR\aaccount\x12<\n" +
	"\vphoneNumber\x18\x03 \x01(\v2\x1a.fdim.protobuf.StringValueR\vphoneNumber\x126\n" +
	"\bareaCode\x18\x04 \x01(\v2\x1a.fdim.protobuf.StringValueR\bareaCode\x120\n" +
	"\x05email\x18\x05 \x01(\v2\x1a.fdim.protobuf.StringValueR\x05email\x126\n" +
	"\bnickname\x18\x06 \x01(\v2\x1a.fdim.protobuf.StringValueR\bnickname\x124\n" +
	"\afaceURL\x18\a \x01(\v2\x1a.fdim.protobuf.StringValueR\afaceURL\x121\n" +
	"\x06gender\x18\b \x01(\v2\x19.fdim.protobuf.Int32ValueR\x06gender\x12/\n" +
	"\x05level\x18\t \x01(\v2\x19.fdim.protobuf.Int32ValueR\x05level\x12/\n" +
	"\x05birth\x18\n" +
	" \x01(\v2\x19.fdim.protobuf.Int64ValueR\x05birth\x12A\n" +
	"\x0eallowAddFriend\x18\v \x01(\v2\x19.fdim.protobuf.Int32ValueR\x0eallowAddFriend\x127\n" +
	"\tallowBeep\x18\f \x01(\v2\x19.fdim.protobuf.Int32ValueR\tallowBeep\x12A\n" +
	"\x0eallowVibration\x18\r \x01(\v2\x19.fdim.protobuf.Int32ValueR\x0eallowVibration\x12E\n" +
	"\x10globalRecvMsgOpt\x18\x0e \x01(\v2\x19.fdim.protobuf.Int32ValueR\x10globalRecvMsgOpt\x12=\n" +
	"\fRegisterType\x18\x0f \x01(\v2\x19.fdim.protobuf.Int32ValueR\fRegisterType\"J\n" +
	"\x12UpdateUserInfoResp\x12\x18\n" +
	"\afaceUrl\x18\x01 \x01(\tR\afaceUrl\x12\x1a\n" +
	"\bnickName\x18\x02 \x01(\tR\bnickName\"1\n" +
	"\x15FindUserPublicInfoReq\x12\x18\n" +
	"\auserIDs\x18\x01 \x03(\tR\auserIDs\"N\n" +
	"\x16FindUserPublicInfoResp\x124\n" +
	"\x05users\x18\x01 \x03(\v2\x1e.fdim.sdkws.ChatUserPublicInfoR\x05users\"\x8c\x01\n" +
	"\x17SearchUserPublicInfoReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.fdim.sdkws.RequestPaginationR\n" +
	"pagination\x12\x18\n" +
	"\agenders\x18\x03 \x01(\x05R\agenders\"f\n" +
	"\x18SearchUserPublicInfoResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\rR\x05total\x124\n" +
	"\x05users\x18\x02 \x03(\v2\x1e.fdim.sdkws.ChatUserPublicInfoR\x05users\"/\n" +
	"\x13FindUserFullInfoReq\x12\x18\n" +
	"\auserIDs\x18\x01 \x03(\tR\auserIDs\"J\n" +
	"\x14FindUserFullInfoResp\x122\n" +
	"\x05users\x18\x01 \x03(\v2\x1c.fdim.sdkws.ChatUserFullInfoR\x05users\"\xf1\x01\n" +
	"\x11SendVerifyCodeReq\x12\x18\n" +
	"\ausedFor\x18\x01 \x01(\x05R\ausedFor\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12&\n" +
	"\x0einvitationCode\x18\x03 \x01(\tR\x0einvitationCode\x12\x1a\n" +
	"\bdeviceID\x18\x04 \x01(\tR\bdeviceID\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\x05R\bplatform\x12\x1a\n" +
	"\bareaCode\x18\x06 \x01(\tR\bareaCode\x12 \n" +
	"\vphoneNumber\x18\a \x01(\tR\vphoneNumber\x12\x14\n" +
	"\x05email\x18\b \x01(\tR\x05email\"\x14\n" +
	"\x12SendVerifyCodeResp\"\x83\x01\n" +
	"\rVerifyCodeReq\x12\x1a\n" +
	"\bareaCode\x18\x01 \x01(\tR\bareaCode\x12 \n" +
	"\vphoneNumber\x18\x02 \x01(\tR\vphoneNumber\x12\x1e\n" +
	"\n" +
	"verifyCode\x18\x03 \x01(\tR\n" +
	"verifyCode\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"\x10\n" +
	"\x0eVerifyCodeResp\"\xbc\x02\n" +
	"\x10RegisterUserInfo\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x18\n" +
	"\afaceURL\x18\x03 \x01(\tR\afaceURL\x12\x14\n" +
	"\x05birth\x18\x04 \x01(\x03R\x05birth\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\x05R\x06gender\x12\x1a\n" +
	"\bareaCode\x18\x06 \x01(\tR\bareaCode\x12 \n" +
	"\vphoneNumber\x18\a \x01(\tR\vphoneNumber\x12\x14\n" +
	"\x05email\x18\b \x01(\tR\x05email\x12\x18\n" +
	"\aaccount\x18\t \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\n" +
	" \x01(\tR\bpassword\x12\"\n" +
	"\fRegisterType\x18\v \x01(\x05R\fRegisterType\"\xf0\x01\n" +
	"\x0fRegisterUserReq\x12&\n" +
	"\x0einvitationCode\x18\x01 \x01(\tR\x0einvitationCode\x12\x1e\n" +
	"\n" +
	"verifyCode\x18\x02 \x01(\tR\n" +
	"verifyCode\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x1a\n" +
	"\bdeviceID\x18\x04 \x01(\tR\bdeviceID\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\x05R\bplatform\x12\x1c\n" +
	"\tautoLogin\x18\x06 \x01(\bR\tautoLogin\x12/\n" +
	"\x04user\x18\a \x01(\v2\x1b.fdim.chat.RegisterUserInfoR\x04user\"H\n" +
	"\x10RegisterUserResp\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1c\n" +
	"\tchatToken\x18\x03 \x01(\tR\tchatToken\"\x8c\x01\n" +
	"\x11AddUserAccountReq\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x1a\n" +
	"\bdeviceID\x18\x02 \x01(\tR\bdeviceID\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\x05R\bplatform\x12/\n" +
	"\x04user\x18\x04 \x01(\v2\x1b.fdim.chat.RegisterUserInfoR\x04user\"\x14\n" +
	"\x12AddUserAccountResp\"\xfc\x01\n" +
	"\bLoginReq\x12\x1a\n" +
	"\bareaCode\x18\x01 \x01(\tR\bareaCode\x12 \n" +
	"\vphoneNumber\x18\x02 \x01(\tR\vphoneNumber\x12\x1e\n" +
	"\n" +
	"verifyCode\x18\x03 \x01(\tR\n" +
	"verifyCode\x12\x18\n" +
	"\aaccount\x18\x04 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x1a\n" +
	"\bplatform\x18\x06 \x01(\x05R\bplatform\x12\x1a\n" +
	"\bdeviceID\x18\a \x01(\tR\bdeviceID\x12\x0e\n" +
	"\x02ip\x18\b \x01(\tR\x02ip\x12\x14\n" +
	"\x05email\x18\t \x01(\tR\x05email\"\xa2\x01\n" +
	"\x10ResetPasswordReq\x12\x1a\n" +
	"\bareaCode\x18\x01 \x01(\tR\bareaCode\x12 \n" +
	"\vphoneNumber\x18\x02 \x01(\tR\vphoneNumber\x12\x1e\n" +
	"\n" +
	"verifyCode\x18\x03 \x01(\tR\n" +
	"verifyCode\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\"\x13\n" +
	"\x11ResetPasswordResp\"w\n" +
	"\x11ChangePasswordReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12(\n" +
	"\x0fcurrentPassword\x18\x02 \x01(\tR\x0fcurrentPassword\x12 \n" +
	"\vnewPassword\x18\x03 \x01(\tR\vnewPassword\"\x14\n" +
	"\x12ChangePasswordResp\".\n" +
	"\x12FindUserAccountReq\x12\x18\n" +
	"\auserIDs\x18\x01 \x03(\tR\auserIDs\"\xb4\x01\n" +
	"\x13FindUserAccountResp\x12Z\n" +
	"\x0euserAccountMap\x18\x01 \x03(\v22.fdim.chat.FindUserAccountResp.UserAccountMapEntryR\x0euserAccountMap\x1aA\n" +
	"\x13UserAccountMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"0\n" +
	"\x12FindAccountUserReq\x12\x1a\n" +
	"\baccounts\x18\x01 \x03(\tR\baccounts\"\xb4\x01\n" +
	"\x13FindAccountUserResp\x12Z\n" +
	"\x0eaccountUserMap\x18\x01 \x03(\v22.fdim.chat.FindAccountUserResp.AccountUserMapEntryR\x0eaccountUserMap\x1aA\n" +
	"\x13AccountUserMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd8\x03\n" +
	"\fSignalRecord\x12\x1a\n" +
	"\bfileName\x18\x01 \x01(\tR\bfileName\x12\x1c\n" +
	"\tmediaType\x18\x02 \x01(\tR\tmediaType\x12\x1a\n" +
	"\broomType\x18\x03 \x01(\tR\broomType\x12\x1a\n" +
	"\bsenderID\x18\x04 \x01(\tR\bsenderID\x12&\n" +
	"\x0esenderNickname\x18\x05 \x01(\tR\x0esenderNickname\x12\x16\n" +
	"\x06recvID\x18\x06 \x01(\tR\x06recvID\x12\"\n" +
	"\frecvNickname\x18\a \x01(\tR\frecvNickname\x12\x18\n" +
	"\agroupID\x18\b \x01(\tR\agroupID\x12\x1c\n" +
	"\tgroupName\x18\t \x01(\tR\tgroupName\x12H\n" +
	"\x0finviterUserList\x18\n" +
	" \x03(\v2\x1e.fdim.sdkws.ChatUserPublicInfoR\x0finviterUserList\x12\x1a\n" +
	"\bduration\x18\v \x01(\x05R\bduration\x12\x1e\n" +
	"\n" +
	"createTime\x18\f \x01(\x03R\n" +
	"createTime\x12\x12\n" +
	"\x04size\x18\r \x01(\tR\x04size\x12 \n" +
	"\vdownloadURL\x18\x0e \x01(\tR\vdownloadURL\"?\n" +
	"\x0fFDIMCallbackReq\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\"\x12\n" +
	"\x10FDIMCallbackResp\"\xa2\x01\n" +
	"\x15SearchUserFullInfoReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.fdim.sdkws.RequestPaginationR\n" +
	"pagination\x12\x18\n" +
	"\agenders\x18\x03 \x01(\x05R\agenders\x12\x16\n" +
	"\x06normal\x18\x04 \x01(\x05R\x06normal\"b\n" +
	"\x16SearchUserFullInfoResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\rR\x05total\x122\n" +
	"\x05users\x18\x02 \x03(\v2\x1c.fdim.sdkws.ChatUserFullInfoR\x05users\";\n" +
	"\x11UserLoginCountReq\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x03R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x03R\x03end\"\xd2\x01\n" +
	"\x12UserLoginCountResp\x12\x1e\n" +
	"\n" +
	"loginCount\x18\x01 \x01(\x03R\n" +
	"loginCount\x12\"\n" +
	"\funloginCount\x18\x02 \x01(\x03R\funloginCount\x12>\n" +
	"\x05count\x18\x03 \x03(\v2(.fdim.chat.UserLoginCountResp.CountEntryR\x05count\x1a8\n" +
	"\n" +
	"CountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"A\n" +
	"\tLoginResp\x12\x1c\n" +
	"\tchatToken\x18\x02 \x01(\tR\tchatToken\x12\x16\n" +
	"\x06userID\x18\x03 \x01(\tR\x06userID\"\xa0\x01\n" +
	"\x11SearchUserInfoReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.fdim.sdkws.RequestPaginationR\n" +
	"pagination\x12\x18\n" +
	"\agenders\x18\x03 \x03(\x05R\agenders\x12\x18\n" +
	"\auserIDs\x18\x04 \x03(\tR\auserIDs\"^\n" +
	"\x12SearchUserInfoResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\rR\x05total\x122\n" +
	"\x05users\x18\x02 \x03(\v2\x1c.fdim.sdkws.ChatUserFullInfoR\x05users\"L\n" +
	"\x1aGetTokenForVideoMeetingReq\x12\x12\n" +
	"\x04room\x18\x01 \x01(\tR\x04room\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\tR\bidentity\"Q\n" +
	"\x1bGetTokenForVideoMeetingResp\x12\x1c\n" +
	"\tserverUrl\x18\x01 \x01(\tR\tserverUrl\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"D\n" +
	"\x11CheckUserExistReq\x12/\n" +
	"\x04user\x18\x01 \x01(\v2\x1b.fdim.chat.RegisterUserInfoR\x04user\"P\n" +
	"\x12CheckUserExistResp\x12\x16\n" +
	"\x06userid\x18\x01 \x01(\tR\x06userid\x12\"\n" +
	"\fisRegistered\x18\x02 \x01(\bR\fisRegistered\"-\n" +
	"\x11DelUserAccountReq\x12\x18\n" +
	"\auserIDs\x18\x01 \x03(\tR\auserIDs\"\x14\n" +
	"\x12DelUserAccountResp\";\n" +
	"\x13SetAllowRegisterReq\x12$\n" +
	"\rallowRegister\x18\x01 \x01(\bR\rallowRegister\"\x16\n" +
	"\x14SetAllowRegisterResp\"\x15\n" +
	"\x13GetAllowRegisterReq\"<\n" +
	"\x14GetAllowRegisterResp\x12$\n" +
	"\rallowRegister\x18\x01 \x01(\bR\rallowRegister2\xf7\r\n" +
	"\x04chat\x12M\n" +
	"\x0eUpdateUserInfo\x12\x1c.fdim.chat.UpdateUserInfoReq\x1a\x1d.fdim.chat.UpdateUserInfoResp\x12M\n" +
	"\x0eAddUserAccount\x12\x1c.fdim.chat.AddUserAccountReq\x1a\x1d.fdim.chat.AddUserAccountResp\x12_\n" +
	"\x14SearchUserPublicInfo\x12\".fdim.chat.SearchUserPublicInfoReq\x1a#.fdim.chat.SearchUserPublicInfoResp\x12Y\n" +
	"\x12FindUserPublicInfo\x12 .fdim.chat.FindUserPublicInfoReq\x1a!.fdim.chat.FindUserPublicInfoResp\x12Y\n" +
	"\x12SearchUserFullInfo\x12 .fdim.chat.SearchUserFullInfoReq\x1a!.fdim.chat.SearchUserFullInfoResp\x12S\n" +
	"\x10FindUserFullInfo\x12\x1e.fdim.chat.FindUserFullInfoReq\x1a\x1f.fdim.chat.FindUserFullInfoResp\x12M\n" +
	"\x0eSendVerifyCode\x12\x1c.fdim.chat.SendVerifyCodeReq\x1a\x1d.fdim.chat.SendVerifyCodeResp\x12A\n" +
	"\n" +
	"VerifyCode\x12\x18.fdim.chat.VerifyCodeReq\x1a\x19.fdim.chat.VerifyCodeResp\x12G\n" +
	"\fRegisterUser\x12\x1a.fdim.chat.RegisterUserReq\x1a\x1b.fdim.chat.RegisterUserResp\x122\n" +
	"\x05Login\x12\x13.fdim.chat.LoginReq\x1a\x14.fdim.chat.LoginResp\x12J\n" +
	"\rResetPassword\x12\x1b.fdim.chat.ResetPasswordReq\x1a\x1c.fdim.chat.ResetPasswordResp\x12M\n" +
	"\x0eChangePassword\x12\x1c.fdim.chat.ChangePasswordReq\x1a\x1d.fdim.chat.ChangePasswordResp\x12M\n" +
	"\x0eCheckUserExist\x12\x1c.fdim.chat.CheckUserExistReq\x1a\x1d.fdim.chat.CheckUserExistResp\x12M\n" +
	"\x0eDelUserAccount\x12\x1c.fdim.chat.DelUserAccountReq\x1a\x1d.fdim.chat.DelUserAccountResp\x12P\n" +
	"\x0fFindUserAccount\x12\x1d.fdim.chat.FindUserAccountReq\x1a\x1e.fdim.chat.FindUserAccountResp\x12P\n" +
	"\x0fFindAccountUser\x12\x1d.fdim.chat.FindAccountUserReq\x1a\x1e.fdim.chat.FindAccountUserResp\x12G\n" +
	"\fFDIMCallback\x12\x1a.fdim.chat.FDIMCallbackReq\x1a\x1b.fdim.chat.FDIMCallbackResp\x12M\n" +
	"\x0eUserLoginCount\x12\x1c.fdim.chat.UserLoginCountReq\x1a\x1d.fdim.chat.UserLoginCountResp\x12M\n" +
	"\x0eSearchUserInfo\x12\x1c.fdim.chat.SearchUserInfoReq\x1a\x1d.fdim.chat.SearchUserInfoResp\x12h\n" +
	"\x17GetTokenForVideoMeeting\x12%.fdim.chat.GetTokenForVideoMeetingReq\x1a&.fdim.chat.GetTokenForVideoMeetingResp\x12S\n" +
	"\x10SetAllowRegister\x12\x1e.fdim.chat.SetAllowRegisterReq\x1a\x1f.fdim.chat.SetAllowRegisterResp\x12S\n" +
	"\x10GetAllowRegister\x12\x1e.fdim.chat.GetAllowRegisterReq\x1a\x1f.fdim.chat.GetAllowRegisterRespB\x14Z\x12fdim/protocol/chatb\x06proto3"

var (
	file_chat_chat_proto_rawDescOnce sync.Once
	file_chat_chat_proto_rawDescData []byte
)

func file_chat_chat_proto_rawDescGZIP() []byte {
	file_chat_chat_proto_rawDescOnce.Do(func() {
		file_chat_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_chat_proto_rawDesc), len(file_chat_chat_proto_rawDesc)))
	})
	return file_chat_chat_proto_rawDescData
}

var file_chat_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 50)
var file_chat_chat_proto_goTypes = []any{
	(*UserIdentity)(nil),                // 0: fdim.chat.UserIdentity
	(*UpdateUserInfoReq)(nil),           // 1: fdim.chat.UpdateUserInfoReq
	(*UpdateUserInfoResp)(nil),          // 2: fdim.chat.UpdateUserInfoResp
	(*FindUserPublicInfoReq)(nil),       // 3: fdim.chat.FindUserPublicInfoReq
	(*FindUserPublicInfoResp)(nil),      // 4: fdim.chat.FindUserPublicInfoResp
	(*SearchUserPublicInfoReq)(nil),     // 5: fdim.chat.SearchUserPublicInfoReq
	(*SearchUserPublicInfoResp)(nil),    // 6: fdim.chat.SearchUserPublicInfoResp
	(*FindUserFullInfoReq)(nil),         // 7: fdim.chat.FindUserFullInfoReq
	(*FindUserFullInfoResp)(nil),        // 8: fdim.chat.FindUserFullInfoResp
	(*SendVerifyCodeReq)(nil),           // 9: fdim.chat.SendVerifyCodeReq
	(*SendVerifyCodeResp)(nil),          // 10: fdim.chat.SendVerifyCodeResp
	(*VerifyCodeReq)(nil),               // 11: fdim.chat.VerifyCodeReq
	(*VerifyCodeResp)(nil),              // 12: fdim.chat.VerifyCodeResp
	(*RegisterUserInfo)(nil),            // 13: fdim.chat.RegisterUserInfo
	(*RegisterUserReq)(nil),             // 14: fdim.chat.RegisterUserReq
	(*RegisterUserResp)(nil),            // 15: fdim.chat.RegisterUserResp
	(*AddUserAccountReq)(nil),           // 16: fdim.chat.AddUserAccountReq
	(*AddUserAccountResp)(nil),          // 17: fdim.chat.AddUserAccountResp
	(*LoginReq)(nil),                    // 18: fdim.chat.LoginReq
	(*ResetPasswordReq)(nil),            // 19: fdim.chat.ResetPasswordReq
	(*ResetPasswordResp)(nil),           // 20: fdim.chat.ResetPasswordResp
	(*ChangePasswordReq)(nil),           // 21: fdim.chat.ChangePasswordReq
	(*ChangePasswordResp)(nil),          // 22: fdim.chat.ChangePasswordResp
	(*FindUserAccountReq)(nil),          // 23: fdim.chat.FindUserAccountReq
	(*FindUserAccountResp)(nil),         // 24: fdim.chat.FindUserAccountResp
	(*FindAccountUserReq)(nil),          // 25: fdim.chat.FindAccountUserReq
	(*FindAccountUserResp)(nil),         // 26: fdim.chat.FindAccountUserResp
	(*SignalRecord)(nil),                // 27: fdim.chat.SignalRecord
	(*FDIMCallbackReq)(nil),             // 28: fdim.chat.FDIMCallbackReq
	(*FDIMCallbackResp)(nil),            // 29: fdim.chat.FDIMCallbackResp
	(*SearchUserFullInfoReq)(nil),       // 30: fdim.chat.SearchUserFullInfoReq
	(*SearchUserFullInfoResp)(nil),      // 31: fdim.chat.SearchUserFullInfoResp
	(*UserLoginCountReq)(nil),           // 32: fdim.chat.UserLoginCountReq
	(*UserLoginCountResp)(nil),          // 33: fdim.chat.UserLoginCountResp
	(*LoginResp)(nil),                   // 34: fdim.chat.LoginResp
	(*SearchUserInfoReq)(nil),           // 35: fdim.chat.SearchUserInfoReq
	(*SearchUserInfoResp)(nil),          // 36: fdim.chat.SearchUserInfoResp
	(*GetTokenForVideoMeetingReq)(nil),  // 37: fdim.chat.GetTokenForVideoMeetingReq
	(*GetTokenForVideoMeetingResp)(nil), // 38: fdim.chat.GetTokenForVideoMeetingResp
	(*CheckUserExistReq)(nil),           // 39: fdim.chat.CheckUserExistReq
	(*CheckUserExistResp)(nil),          // 40: fdim.chat.CheckUserExistResp
	(*DelUserAccountReq)(nil),           // 41: fdim.chat.DelUserAccountReq
	(*DelUserAccountResp)(nil),          // 42: fdim.chat.DelUserAccountResp
	(*SetAllowRegisterReq)(nil),         // 43: fdim.chat.SetAllowRegisterReq
	(*SetAllowRegisterResp)(nil),        // 44: fdim.chat.SetAllowRegisterResp
	(*GetAllowRegisterReq)(nil),         // 45: fdim.chat.GetAllowRegisterReq
	(*GetAllowRegisterResp)(nil),        // 46: fdim.chat.GetAllowRegisterResp
	nil,                                 // 47: fdim.chat.FindUserAccountResp.UserAccountMapEntry
	nil,                                 // 48: fdim.chat.FindAccountUserResp.AccountUserMapEntry
	nil,                                 // 49: fdim.chat.UserLoginCountResp.CountEntry
	(*wrapperspb.StringValue)(nil),      // 50: fdim.protobuf.StringValue
	(*wrapperspb.Int32Value)(nil),       // 51: fdim.protobuf.Int32Value
	(*wrapperspb.Int64Value)(nil),       // 52: fdim.protobuf.Int64Value
	(*sdkws.ChatUserPublicInfo)(nil),    // 53: fdim.sdkws.ChatUserPublicInfo
	(*sdkws.RequestPagination)(nil),     // 54: fdim.sdkws.RequestPagination
	(*sdkws.ChatUserFullInfo)(nil),      // 55: fdim.sdkws.ChatUserFullInfo
}
var file_chat_chat_proto_depIdxs = []int32{
	50, // 0: fdim.chat.UpdateUserInfoReq.account:type_name -> fdim.protobuf.StringValue
	50, // 1: fdim.chat.UpdateUserInfoReq.phoneNumber:type_name -> fdim.protobuf.StringValue
	50, // 2: fdim.chat.UpdateUserInfoReq.areaCode:type_name -> fdim.protobuf.StringValue
	50, // 3: fdim.chat.UpdateUserInfoReq.email:type_name -> fdim.protobuf.StringValue
	50, // 4: fdim.chat.UpdateUserInfoReq.nickname:type_name -> fdim.protobuf.StringValue
	50, // 5: fdim.chat.UpdateUserInfoReq.faceURL:type_name -> fdim.protobuf.StringValue
	51, // 6: fdim.chat.UpdateUserInfoReq.gender:type_name -> fdim.protobuf.Int32Value
	51, // 7: fdim.chat.UpdateUserInfoReq.level:type_name -> fdim.protobuf.Int32Value
	52, // 8: fdim.chat.UpdateUserInfoReq.birth:type_name -> fdim.protobuf.Int64Value
	51, // 9: fdim.chat.UpdateUserInfoReq.allowAddFriend:type_name -> fdim.protobuf.Int32Value
	51, // 10: fdim.chat.UpdateUserInfoReq.allowBeep:type_name -> fdim.protobuf.Int32Value
	51, // 11: fdim.chat.UpdateUserInfoReq.allowVibration:type_name -> fdim.protobuf.Int32Value
	51, // 12: fdim.chat.UpdateUserInfoReq.globalRecvMsgOpt:type_name -> fdim.protobuf.Int32Value
	51, // 13: fdim.chat.UpdateUserInfoReq.RegisterType:type_name -> fdim.protobuf.Int32Value
	53, // 14: fdim.chat.FindUserPublicInfoResp.users:type_name -> fdim.sdkws.ChatUserPublicInfo
	54, // 15: fdim.chat.SearchUserPublicInfoReq.pagination:type_name -> fdim.sdkws.RequestPagination
	53, // 16: fdim.chat.SearchUserPublicInfoResp.users:type_name -> fdim.sdkws.ChatUserPublicInfo
	55, // 17: fdim.chat.FindUserFullInfoResp.users:type_name -> fdim.sdkws.ChatUserFullInfo
	13, // 18: fdim.chat.RegisterUserReq.user:type_name -> fdim.chat.RegisterUserInfo
	13, // 19: fdim.chat.AddUserAccountReq.user:type_name -> fdim.chat.RegisterUserInfo
	47, // 20: fdim.chat.FindUserAccountResp.userAccountMap:type_name -> fdim.chat.FindUserAccountResp.UserAccountMapEntry
	48, // 21: fdim.chat.FindAccountUserResp.accountUserMap:type_name -> fdim.chat.FindAccountUserResp.AccountUserMapEntry
	53, // 22: fdim.chat.SignalRecord.inviterUserList:type_name -> fdim.sdkws.ChatUserPublicInfo
	54, // 23: fdim.chat.SearchUserFullInfoReq.pagination:type_name -> fdim.sdkws.RequestPagination
	55, // 24: fdim.chat.SearchUserFullInfoResp.users:type_name -> fdim.sdkws.ChatUserFullInfo
	49, // 25: fdim.chat.UserLoginCountResp.count:type_name -> fdim.chat.UserLoginCountResp.CountEntry
	54, // 26: fdim.chat.SearchUserInfoReq.pagination:type_name -> fdim.sdkws.RequestPagination
	55, // 27: fdim.chat.SearchUserInfoResp.users:type_name -> fdim.sdkws.ChatUserFullInfo
	13, // 28: fdim.chat.CheckUserExistReq.user:type_name -> fdim.chat.RegisterUserInfo
	1,  // 29: fdim.chat.chat.UpdateUserInfo:input_type -> fdim.chat.UpdateUserInfoReq
	16, // 30: fdim.chat.chat.AddUserAccount:input_type -> fdim.chat.AddUserAccountReq
	5,  // 31: fdim.chat.chat.SearchUserPublicInfo:input_type -> fdim.chat.SearchUserPublicInfoReq
	3,  // 32: fdim.chat.chat.FindUserPublicInfo:input_type -> fdim.chat.FindUserPublicInfoReq
	30, // 33: fdim.chat.chat.SearchUserFullInfo:input_type -> fdim.chat.SearchUserFullInfoReq
	7,  // 34: fdim.chat.chat.FindUserFullInfo:input_type -> fdim.chat.FindUserFullInfoReq
	9,  // 35: fdim.chat.chat.SendVerifyCode:input_type -> fdim.chat.SendVerifyCodeReq
	11, // 36: fdim.chat.chat.VerifyCode:input_type -> fdim.chat.VerifyCodeReq
	14, // 37: fdim.chat.chat.RegisterUser:input_type -> fdim.chat.RegisterUserReq
	18, // 38: fdim.chat.chat.Login:input_type -> fdim.chat.LoginReq
	19, // 39: fdim.chat.chat.ResetPassword:input_type -> fdim.chat.ResetPasswordReq
	21, // 40: fdim.chat.chat.ChangePassword:input_type -> fdim.chat.ChangePasswordReq
	39, // 41: fdim.chat.chat.CheckUserExist:input_type -> fdim.chat.CheckUserExistReq
	41, // 42: fdim.chat.chat.DelUserAccount:input_type -> fdim.chat.DelUserAccountReq
	23, // 43: fdim.chat.chat.FindUserAccount:input_type -> fdim.chat.FindUserAccountReq
	25, // 44: fdim.chat.chat.FindAccountUser:input_type -> fdim.chat.FindAccountUserReq
	28, // 45: fdim.chat.chat.FDIMCallback:input_type -> fdim.chat.FDIMCallbackReq
	32, // 46: fdim.chat.chat.UserLoginCount:input_type -> fdim.chat.UserLoginCountReq
	35, // 47: fdim.chat.chat.SearchUserInfo:input_type -> fdim.chat.SearchUserInfoReq
	37, // 48: fdim.chat.chat.GetTokenForVideoMeeting:input_type -> fdim.chat.GetTokenForVideoMeetingReq
	43, // 49: fdim.chat.chat.SetAllowRegister:input_type -> fdim.chat.SetAllowRegisterReq
	45, // 50: fdim.chat.chat.GetAllowRegister:input_type -> fdim.chat.GetAllowRegisterReq
	2,  // 51: fdim.chat.chat.UpdateUserInfo:output_type -> fdim.chat.UpdateUserInfoResp
	17, // 52: fdim.chat.chat.AddUserAccount:output_type -> fdim.chat.AddUserAccountResp
	6,  // 53: fdim.chat.chat.SearchUserPublicInfo:output_type -> fdim.chat.SearchUserPublicInfoResp
	4,  // 54: fdim.chat.chat.FindUserPublicInfo:output_type -> fdim.chat.FindUserPublicInfoResp
	31, // 55: fdim.chat.chat.SearchUserFullInfo:output_type -> fdim.chat.SearchUserFullInfoResp
	8,  // 56: fdim.chat.chat.FindUserFullInfo:output_type -> fdim.chat.FindUserFullInfoResp
	10, // 57: fdim.chat.chat.SendVerifyCode:output_type -> fdim.chat.SendVerifyCodeResp
	12, // 58: fdim.chat.chat.VerifyCode:output_type -> fdim.chat.VerifyCodeResp
	15, // 59: fdim.chat.chat.RegisterUser:output_type -> fdim.chat.RegisterUserResp
	34, // 60: fdim.chat.chat.Login:output_type -> fdim.chat.LoginResp
	20, // 61: fdim.chat.chat.ResetPassword:output_type -> fdim.chat.ResetPasswordResp
	22, // 62: fdim.chat.chat.ChangePassword:output_type -> fdim.chat.ChangePasswordResp
	40, // 63: fdim.chat.chat.CheckUserExist:output_type -> fdim.chat.CheckUserExistResp
	42, // 64: fdim.chat.chat.DelUserAccount:output_type -> fdim.chat.DelUserAccountResp
	24, // 65: fdim.chat.chat.FindUserAccount:output_type -> fdim.chat.FindUserAccountResp
	26, // 66: fdim.chat.chat.FindAccountUser:output_type -> fdim.chat.FindAccountUserResp
	29, // 67: fdim.chat.chat.FDIMCallback:output_type -> fdim.chat.FDIMCallbackResp
	33, // 68: fdim.chat.chat.UserLoginCount:output_type -> fdim.chat.UserLoginCountResp
	36, // 69: fdim.chat.chat.SearchUserInfo:output_type -> fdim.chat.SearchUserInfoResp
	38, // 70: fdim.chat.chat.GetTokenForVideoMeeting:output_type -> fdim.chat.GetTokenForVideoMeetingResp
	44, // 71: fdim.chat.chat.SetAllowRegister:output_type -> fdim.chat.SetAllowRegisterResp
	46, // 72: fdim.chat.chat.GetAllowRegister:output_type -> fdim.chat.GetAllowRegisterResp
	51, // [51:73] is the sub-list for method output_type
	29, // [29:51] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_chat_chat_proto_init() }
func file_chat_chat_proto_init() {
	if File_chat_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_chat_proto_rawDesc), len(file_chat_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   50,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_chat_proto_goTypes,
		DependencyIndexes: file_chat_chat_proto_depIdxs,
		MessageInfos:      file_chat_chat_proto_msgTypes,
	}.Build()
	File_chat_chat_proto = out.File
	file_chat_chat_proto_goTypes = nil
	file_chat_chat_proto_depIdxs = nil
}
