name: fdim_app
description: "FDIM - Instant Messaging App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # 状态管理 & 路由
  get: ^4.6.6
  # 网络
  dio: ^5.7.0
  web_socket_channel: ^3.0.1
  # 本地存储
  shared_preferences: ^2.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # UI
  flutter_screenutil: ^5.9.3
  flutter_easyloading: ^3.0.5
  cached_network_image: ^3.4.1
  # 工具
  uuid: ^4.5.1
  crypto: ^3.0.6
  intl: ^0.20.2
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  pull_to_refresh_notification: ^3.1.0
  rxdart: ^0.28.0
  focus_detector_v2: ^3.1.0+1
  persistent_bottom_nav_bar_v2: ^5.3.1
  photo_view: ^0.15.0
  video_player: ^2.9.2
  chewie: ^1.8.5
  just_audio: ^0.9.42
  url_launcher: ^6.3.1
  record: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
